---
- name: Ejecutar PowerShell en Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Hacer ping a los hosts Windows
      ansible.windows.win_ping:

    - name: Ejecutar script PowerShell en Desktop
      ansible.windows.win_powershell:
        script: |
          & "C:\NOC\NOC_SCRIPTS\ScriptLog.ps1"
